CREATE DATABASE HOTEL;
-- USE HOTEL;

-- BRANCH TABLE
CREATE TABLE BRANCH
(
B_ID INT PRIMARY KEY,
B_NAME NVARCHAR(10),
B_Location NVARCHAR(100) 
);

-- STAFF TABLE
CREATE TABLE STAFF
(
S_ID INT PRIMARY KEY,
S_NAME NVARCHAR(100),
Job_Title NVARCHAR(50),
Salary DECIMAL(10, 2) CHECK (Salary >= 600 AND Salary <= 1500),
B_ID INT,
FOREIGN KEY (B_ID) REFERENCES BRANCH(B_ID)
);

-- ROOMS TABLE
CREATE TABLE ROOMS 
(
R_NUM INT PRIMARY KEY,
Type VARCHAR(50),
NIGHTLY_RATY DECIMAL(10, 2),
B_ID INT,
FOREIGN KEY (B_ID) REFERENCES BRANCH(B_ID)
);

-- CUSTOMER TABLE
CREATE TABLE CUSTOMER 
(
C_ID INT PRIMARY KEY,
C_Name VARCHAR(100),
Email VARCHAR(100),
Phone VARCHAR(20)
);

-- BOOKING TABLE (associative entity)
CREATE TABLE BOOKING 
(
Booking_ID INT PRIMARY KEY,
Check_in DATE,
Check_out DATE,
Availability CHAR(1) CHECK (Availability IN ('Y','N')),
C_ID INT,
R_NUM INT,
FOREIGN KEY (C_ID) REFERENCES CUSTOMER(C_ID),
FOREIGN KEY (R_NUM) REFERENCES ROOMS(R_NUM)
);